version: 2.1

jobs:
  # Job to check out the code and install dependencies for both backend and frontend
  install-dependencies:
    docker:
      - image: cimg/node:16.13.0  # Node image for frontend and backend
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          working_directory: ~/BACKEND
          command: npm install
      - run:
          name: Install Frontend Dependencies
          working_directory: ~/frontend
          command: npm install

  # Job to run backend tests
  backend-tests:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run:
          name: Run Backend Tests
          working_directory: ~/BACKEND
          command: npm test

  # Job to run frontend tests
  frontend-tests:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run:
          name: Run Frontend Tests
          working_directory: ~/frontend
          command: npm test

  # Job to perform linting
  lint:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run:
          name: Lint Backend
          working_directory: ~/BACKEND
          command: npm run lint
      - run:
          name: Lint Frontend
          working_directory: ~/frontend
          command: npm run lint

  # Job for SonarQube analysis
  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - checkout
      - run: find .
      - run:
          name: Run SonarQube Analysis
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: " $SONAR_BRANCH
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  version: 2
  test-and-analyze:
    jobs:
      - install-dependencies
      - backend-tests:
          requires:
            - install-dependencies
      - frontend-tests:
          requires:
            - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - sonarqube:
          requires:
            - backend-tests
            - frontend-tests
            - lint
