version: 2.1

jobs:
  # Job for backend testing and setup
  backend-setup:
    docker:
      - image: cimg/node:current
    working_directory: ~/project/backend  # Set the working directory to backend
    steps:
      - checkout
      - run:
          name: "Install jq"
          command: "sudo apt-get update && sudo apt-get install -y jq"
      - run:
          name: "Install Backend Dependencies"
          command: "npm install"  # Install dependencies
      - run:
          name: "Start Backend Server"
          command: "npm start &"  # Start backend server in the background
          background: true
      - run:
          name: "Wait for Backend Server"
          command: |
            echo "Waiting for backend to be ready..."
            for i in $(seq 1 30); do  # Increased the number of attempts from 15 to 30
              if curl --silent --fail http://localhost:3001/csrf-token; then
                echo "Backend server is ready."
                break
              fi
              echo "Waiting for backend (attempt $i)..."
              sleep 10
            done || (echo "Backend server failed to start." && exit 1)
      - run:
          name: "Get CSRF Token and Store"
          command: |
            echo "Fetching CSRF token..."
            export CSRF_TOKEN=$(curl -s -X GET http://localhost:3001/csrf-token | jq -r '.csrfToken')
            if [ -z "$CSRF_TOKEN" ] || [ "$CSRF_TOKEN" == "null" ]; then
              echo "Failed to get CSRF token"
              exit 1
            fi
            echo "CSRF token fetched successfully: $CSRF_TOKEN"
            echo 'export CSRF_TOKEN='$CSRF_TOKEN >> $BASH_ENV
      - run:
          name: "Get JWT Token and Store"
          command: |
            echo "Fetching JWT token..."
            export LOGIN_PAYLOAD='{ "username": "testuser", "accountNumber": "123456", "password": "password" }'
            export JWT_TOKEN=$(curl -s -X POST http://localhost:3001/users/login -H "Content-Type: application/json" -H "X-CSRF-Token: $CSRF_TOKEN" -d "$LOGIN_PAYLOAD" | jq -r '.token')
            if [ -z "$JWT_TOKEN" ] || [ "$JWT_TOKEN" == "null" ];then
              echo "Failed to get JWT token"
              exit 1
            fi
            echo "JWT token fetched successfully: $JWT_TOKEN"
            echo 'export JWT_TOKEN='$JWT_TOKEN >> $BASH_ENV
      - run:
          name: "Run Basic Backend Tests"
          command: |
            echo "Testing backend endpoints..."
            curl --fail http://localhost:3001/users/login || (echo "Login endpoint failed!" && exit 1)
            curl --fail -H "Authorization: Bearer $JWT_TOKEN" http://localhost:3001/payments || (echo "Payments endpoint failed!" && exit 1)
            curl --fail -H "Authorization: Bearer $JWT_TOKEN" http://localhost:3001/employee/payments || (echo "Employee payments endpoint failed!" && exit 1)
            echo "Backend tests completed successfully."

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - backend-setup
